version: '3.8'

services:
  boardcontinuity:
    build: .
    container_name: boardcontinuity-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE=${SUPABASE_SERVICE_ROLE}
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - DEV_ORG_ID=${DEV_ORG_ID}
      - DEV_USER_ID=${DEV_USER_ID}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - boardcontinuity-network

  nginx:
    image: nginx:alpine
    container_name: boardcontinuity-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
      - ./static:/var/www/static:ro
    depends_on:
      - boardcontinuity
    restart: unless-stopped
    networks:
      - boardcontinuity-network

  redis:
    image: redis:alpine
    container_name: boardcontinuity-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - boardcontinuity-network

networks:
  boardcontinuity-network:
    driver: bridge

volumes:
  redis-data: